#!/usr/bin/env perl

use strict;
use warnings;
use POSIX qw(strftime);

my $date = strftime '%Y-%m-%d-%H%M%S', localtime;
my $path=$ENV{"HOME"}."/Pictures/screenshots/$date.png";
system ("maim", "-s", $path, "--hidecursor") and die;
system ("xclip", "-selection", "clipboard", "-t", "image/png", $path) and die;
system ("feh", $path);
